// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesAnalyticsETL.Infrastructure.context;

#nullable disable

namespace SalesAnalyticsETL.Infrastructure.Migrations
{
    [DbContext(typeof(DataWarehouseContext))]
    [Migration("20251204030703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesAnalyticsETL.Domain.Entities.DimCliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClienteID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Dim_Cliente_Email");

                    b.ToTable("Dim_Cliente");
                });

            modelBuilder.Entity("SalesAnalyticsETL.Domain.Entities.DimEstado", b =>
                {
                    b.Property<int>("EstadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoID");

                    b.ToTable("Dim_Estado");

                    b.HasData(
                        new
                        {
                            EstadoID = 1,
                            Activo = true,
                            Descripcion = "Orden pendiente de procesamiento",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreEstado = "PENDIENTE"
                        },
                        new
                        {
                            EstadoID = 2,
                            Activo = true,
                            Descripcion = "Orden en proceso",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreEstado = "PROCESANDO"
                        },
                        new
                        {
                            EstadoID = 3,
                            Activo = true,
                            Descripcion = "Orden completada exitosamente",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreEstado = "COMPLETADO"
                        },
                        new
                        {
                            EstadoID = 4,
                            Activo = true,
                            Descripcion = "Orden cancelada",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreEstado = "CANCELADO"
                        },
                        new
                        {
                            EstadoID = 5,
                            Activo = true,
                            Descripcion = "Orden devuelta",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreEstado = "DEVUELTO"
                        });
                });

            modelBuilder.Entity("SalesAnalyticsETL.Domain.Entities.DimProducto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoID"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductoID");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_Dim_Producto_Categoria");

                    b.HasIndex("NombreProducto")
                        .HasDatabaseName("IX_Dim_Producto_Nombre");

                    b.ToTable("Dim_Producto");
                });

            modelBuilder.Entity("SalesAnalyticsETL.Domain.Entities.DimTiempo", b =>
                {
                    b.Property<int>("TiempoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TiempoID"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("EsFeriado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsFinDeSemana")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NombreMes")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Trimestre")
                        .HasColumnType("int");

                    b.HasKey("TiempoID");

                    b.HasIndex("Fecha")
                        .IsUnique()
                        .HasDatabaseName("IX_Dim_Tiempo_Fecha");

                    b.HasIndex("Anio", "Mes")
                        .HasDatabaseName("IX_Dim_Tiempo_AnioMes");

                    b.ToTable("Dim_Tiempo");
                });

            modelBuilder.Entity("SalesAnalyticsETL.Domain.Entities.FactVentas", b =>
                {
                    b.Property<int>("VentaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrdenID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoID")
                        .HasColumnType("int");

                    b.Property<int>("TiempoID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalVenta")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VentaID");

                    b.HasIndex("ClienteID")
                        .HasDatabaseName("IX_Fact_Ventas_ClienteID");

                    b.HasIndex("EstadoID");

                    b.HasIndex("OrdenID")
                        .IsUnique()
                        .HasDatabaseName("IX_Fact_Ventas_OrdenID");

                    b.HasIndex("ProductoID")
                        .HasDatabaseName("IX_Fact_Ventas_ProductoID");

                    b.HasIndex("TiempoID")
                        .HasDatabaseName("IX_Fact_Ventas_TiempoID");

                    b.HasIndex("ClienteID", "ProductoID", "TiempoID")
                        .HasDatabaseName("IX_Fact_Ventas_Dimensions");

                    b.ToTable("Fact_Ventas");
                });

            modelBuilder.Entity("SalesAnalyticsETL.Domain.Entities.FactVentas", b =>
                {
                    b.HasOne("SalesAnalyticsETL.Domain.Entities.DimCliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesAnalyticsETL.Domain.Entities.DimEstado", "Estado")
                        .WithMany("Ventas")
                        .HasForeignKey("EstadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesAnalyticsETL.Domain.Entities.DimProducto", "Producto")
                        .WithMany("Ventas")
                        .HasForeignKey("ProductoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesAnalyticsETL.Domain.Entities.DimTiempo", "Tiempo")
                        .WithMany("Ventas")
                        .HasForeignKey("TiempoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estado");

                    b.Navigation("Producto");

                    b.Navigation("Tiempo");
                });

            modelBuilder.Entity("SalesAnalyticsETL.Domain.Entities.DimCliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SalesAnalyticsETL.Domain.Entities.DimEstado", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SalesAnalyticsETL.Domain.Entities.DimProducto", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SalesAnalyticsETL.Domain.Entities.DimTiempo", b =>
                {
                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
